### ISSUE TITLE
n_clusters

### ISSUE THREAD

**Issue by jxthyatt** [zshuai8/FedGMM_ICML2023#3]
If we set n_clusters=3 (n_component=3) when generating non-iid clients, then theoretically how to set n_learner and n_gmm to get best results? is n_learner=3 and n_gmm=3 right? 
Please help to understand relations between the n_clusters and the n_learner, n_gmm?

**Comment by zshuai8** [comment]
Depends on the input distribution of each cluster. If indeed n_cluster=3, and the input distribution is Gaussian, then n_gmm=3 is optimal.

**Comment by zshuai8** [comment]
Depends on the input distribution of each cluster. If indeed n_cluster=3, and the input distribution is Gaussian, then n_gmm=3 is optimal. As for the relationship between the n_clusters and the n_learner, n_gmm, you might have to verify via empirical experiment results.
